ridge_alpha_start = input("Ridge alpha start : ")
ridge_alpha_end = input("Ridge alpha end : ")
ridge_alpha_step = input("Ridge alpha step : ")
lasso_alpha_start = input("Lasso alpha start : ")
lasso_alpha_end = input("Lasso alpha end : ")
lasso_alpha_step = input("Lasso alpha step : ")
